# makefile test for hello program
#written by Emdoor
CC = gcc

# all: hello

TEST_TAR += test.exe
TEST_SRC += test.c
TEST_SRC += ../../revlib/ASA/ASA_UARTS.c
TEST_SRC += ../../revlib/ASA/buffer.c
# TEST_SRC += text.c

test:
	$(CC) $(TEST_SRC) -o $(TEST_TAR)
